platform :ios, '9.0'
react_native_path = "../node_modules/react-native"
project "AgoraRNQuickStart.xcodeproj"

target 'AgoraRNQuickStart' do
  pod "react-native-agora", path: "../node_modules/react-native-agora"
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  rn_path = "../node_modules/react-native"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/folly.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end
end
