platform :ios, '9.0'
react_native_path = "../node_modules/react-native"
project "AgoraRNQuickStart.xcodeproj"

target 'AgoraRNQuickStart' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AgoraRNQuickStart

  #target 'AgoraRNQuickStart-tvOSTests' do
  #  inherit! :search_paths
  #  # Pods for testing
  #end
  pod "react-native-agora", path: "../node_modules/react-native-agora"
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', path: '../node_modules/react-native'
  #pod "React", path: react_native_path
  #%w(DoubleConversion Folly glog).each do |lib_name|
  #  pod lib_name, podspec: "#{react_native_path}/third-party-podspecs/#{lib_name}.podspec"
  #end

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'AgoraRNQuickStartTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AgoraRNQuickStart-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AgoraRNQuickStart-tvOS

  target 'AgoraRNQuickStart-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
